name: build

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, pdo, pdo_mysql, intl, zip, libxml, dom, json
          coverage: none

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check PHP Extensions
        run: php -m

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Disable testing for now due to rate limiting and other issues from GH workers
      # Instead run tests manually on local machine before publishing, but even there it's not 100% reliable due to nature of crawling
      # TODO to maintain this project easier, maybe consider using only API when it's possible and and remove html parsing all together
      # (keep only for providers when there is no API or API is paid as a backup)
      # - name: Run test suite
      #   run: vendor/bin/phpunit
